version: '2.3'
services:

  users:
    build:
      context: .
      dockerfile: prod/users/Dockerfile
    ports:
      - "8080:8080"
    restart: always
    links:
      - "db:db"
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8080"]
      
  db:
    image: mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: nbx
      MYSQL_PASSWORD: crypto
      MYSQL_DATABASE: nbx
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - "./users/db:/docker-entrypoint-initdb.d:rw"
      - "./data:/var/lib/mysql:rw"
